「WIP」chat space viewの実装
mtronfuyu/chat-space pull request #3
Opened 2019-05-21 12:09 UTC by mtronfuyu

# WHAT
chat space viewの実装

# WAY
必須の機能であるため

## chat spaceの実装画面のURL
http://localhost:3000/?

2019-05-22 03:46 UTC, TOMARUMARU commented on app/views/messages/index.html.haml
> +  %body
ここから上の記述は不要なはずです

2019-05-22 03:46 UTC, TOMARUMARU commented on app/views/messages/index.html.haml
> +          %a(class="fas fa-edit" href="")
link_toを使いましょう。他の箇所も同様です

2019-05-24 12:03 UTC, mtronfuyu commented on app/views/messages/index.html.haml
> +  %body
指摘箇所削除しました

2019-05-24 12:05 UTC, mtronfuyu commented on app/views/messages/index.html.haml
> +          %a(class="fas fa-edit" href="")
aタグ使用箇所全てlink_toに書き直しました

2019-05-24 12:08 UTC, TOMARUMARU commented
修正が反映されていないようなので、pushしてください！

2019-05-25 12:31 UTC, miyagit commented on app/assets/stylesheets/_main-chat.scss
> +      padding: 10px 40px 40px 40px;
padding: 10px 40pxにしましょう。

2019-05-26 02:07 UTC, mtronfuyu commented on app/assets/stylesheets/_main-chat.scss
> +      padding: 10px 40px 40px 40px;
指定箇所　padding: 10px 40;
に修正しました。

2019-05-26 02:10 UTC, ghost requested changes
実際の画面のキャプチャをこちらに添付してください

2019-05-26 03:16 UTC, mtronfuyu commented
http://localhost:3000/

2019-05-26 03:20 UTC, ghost requested changes

2019-05-26 03:20 UTC, hiroki5123 commented on app/assets/stylesheets/_form.scss
> +form {
できればformタグにもクラスをつけて、タグ指定ではなくクラス指定でcssを書きましょう

2019-05-26 03:20 UTC, hiroki5123 commented on app/views/messages/index.html.haml
> +      %input(class="input-text"type="text" id="message" placeholder="Type a message")
カッコ省略しましょう

2019-05-26 03:20 UTC, hiroki5123 commented on app/views/messages/index.html.haml
> +          %span(class="filelabel")
ここら辺も

2019-05-26 10:30 UTC, mtronfuyu commented on app/views/messages/index.html.haml
> +          %span(class="filelabel")
ハッシュで書くということですか？

2019-05-26 11:49 UTC, kuroko918 commented on app/assets/stylesheets/_form.scss
> +form {
こちらお願いします

2019-05-26 11:50 UTC, kuroko918 commented on app/views/messages/index.html.haml
> +      %input(class="input-text"type="text" id="message" placeholder="Type a message")
%input#message.input-text{type: “text”, placeholder: “Type a message”} と書けますね

2019-05-26 11:51 UTC, kuroko918 commented on app/views/messages/index.html.haml
> +          %span(class="filelabel")
こちらも同様に変更お願いします

2019-05-26 21:55 UTC, mtronfuyu commented
指摘箇所、修正しました。
https://github.com/mtronfuyu/chat-space/pull/3

2019-05-27 02:10 UTC, kuroko918 commented
LGTMです！

2019-06-21 11:50 UTC, merged